/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 palette
        'primary': '#11af4e',
        'primary-container': '#7ec882',
        'on-primary': '#ffffff',
        'on-primary-container': '#0a5e2a',
        'on-primary-fixed': '#0a5e2a',
        'on-primary-fixed-variant': '#0d8a3c',
        'primary-fixed': '#c6e1c8',
        'primary-fixed-dim': '#7ec882',
        'secondary': '#545f73',
        'secondary-container': '#d5e0f8',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#586377',
        'on-secondary-fixed': '#111c2d',
        'on-secondary-fixed-variant': '#3c475a',
        'secondary-fixed': '#d8e3fb',
        'secondary-fixed-dim': '#bcc7de',
        'tertiary': '#11af4e',
        'tertiary-container': '#7ec882',
        'tertiary-fixed': '#c6e1c8',
        'tertiary-fixed-dim': '#7ec882',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#003c12',
        'on-tertiary-fixed': '#002107',
        'on-tertiary-fixed-variant': '#07521d',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'surface': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-variant': '#e0e3e5',
        'surface-tint': '#11af4e',
        'surface-container': '#eceef0',
        'surface-container-low': '#f2f4f6',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'surface-container-lowest': '#ffffff',
        'on-surface': '#191c1e',
        'on-surface-variant': '#3f4a3c',
        'accent': '#c6e1c8',
        'accent-dark': '#7ec882',
        'on-background': '#191c1e',
        'background': '#f7f9fb',
        'outline': '#6f7a6b',
        'outline-variant': '#becab9',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        'inverse-primary': '#7ec882',
        // Legacy aliases for sub-pages compatibility
        'saccs-white': '#ffffff',
        'saccs-light': '#f2f4f6',
        'saccs-grey': '#3f4a3c',
        'saccs-dark': '#191c1e',
        'saccs-text': '#191c1e',
        'icon-bg': '#e6e8ea',
        'forest': '#0d2117',
        'forest-card': '#10291e',
      },
      fontFamily: {
        sans: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        heading: ['var(--font-poppins)', 'Poppins', 'sans-serif'],
        headline: ['var(--font-poppins)', 'Poppins', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '1.5rem',
        full: '9999px',
      },
      animation: {
        'fade-in-up': 'fadeInUp 0.6s ease forwards',
        'scroll': 'scroll 40s linear infinite',
      },
      keyframes: {
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        scroll: {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(calc(-100% / 4))' },
        },
      },
      boxShadow: {
        'saccs-sm': '0 1px 3px rgba(0, 0, 0, 0.06)',
        'saccs-md': '0 2px 8px rgba(0, 0, 0, 0.08)',
        'saccs-lg': '0 4px 12px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
};
